### ISSUE TITLE
最近执行一直提示错误

### ISSUE THREAD

**Issue by zh000323** [gacjie/cf2dns#10]
★[2024-06-28 00:04:33] Successful
----------------------------------------------------------------------------
本次将等待60.02849311202232秒执行
Traceback (most recent call last):
  File "/www/server/panel/plugin/cf2dns/cf2dns.py", line 13, in <module>
    from dns.aliyun import AliApi
  File "/www/server/panel/plugin/cf2dns/dns/aliyun.py", line 7, in <module>
    from aliyunsdkcore import client
  File "/www/server/panel/pyenv/lib/python3.12/site-packages/aliyunsdkcore/client.py", line 31, in <module>
    from aliyunsdkcore.vendored.six.moves.urllib.parse import urlencode
ModuleNotFoundError: No module named 'aliyunsdkcore.vendored.six.moves'

**Comment by gacjie** [comment]
这是因为aapanel升级运行环境为python3.12 目前1.6版本已修复

https://github.com/gacjie/cf2dns/releases/latest
